#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 30 20:22:40 2022

@author: monamez
"""

from matplotlib import pyplot as plt
import numpy as np
import networkx as nx


import sys 
import os

filename = '__file__'
foldername = os.path.dirname( filename )

sys.path.append( foldername )



import watts_strogatz_MA as wsa

n= 50
k = 5
p = 0.1

#Creating Arbitrary Graph
G = wsa.watts_strogatz(n, k, p)
fig,ax = plt.subplots(1,1, figsize=(6,6), constrained_layout=True)


#Graphing Clustering Coefficient
trials = 100
clustering, x =wsa.average_clustering(n,k,trials)

xval = np.array(x)
y = np.array(clustering)

plt.plot(x, y)
plt.xscale('log')
plt.show()


