#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 30 20:22:40 2022

@author: monamez
"""

from matplotlib import pyplot
import numpy as np
import networkx as nx

import sys 
sys.path.append("/Users/monamez/Documents/GitHub/template_watts_strogatz/watts_strogatz_MA.py")
import watts_strogatz_MA as wsa

G = wsa.watts_strogatz(50, 5, 1)

fig,ax = pyplot.subplots(1,1, figsize=(6,6), constrained_layout=True)

nx.draw_circular(G, ax=ax)

fig.show()

